function cases = get_derived_shape_contract_cases
% get_derived_shape_contract_cases lists the concrete Shape subclasses that
% should be checked against the inherited Shape contract.
%
% Update this file when a concrete subclass is added or removed.
% Each field name becomes a separate reported test parameter in the
% parameterized test suite. Each field value must provide:
%   - a factory for the default constructor call
%   - a factory that creates the object with a chosen scale factor
    cases = struct( ...
        'Square', struct( ...
            'createDefault', @() Square(), ...
            'createWithScale', @(scaleFactor) Square(1, scaleFactor) ...
        ), ...
        'Rectangle', struct( ...
            'createDefault', @() Rectangle(), ...
            'createWithScale', @(scaleFactor) Rectangle(1, 1, scaleFactor) ...
        ), ...
        'Circle', struct( ...
            'createDefault', @() Circle(), ...
            'createWithScale', @(scaleFactor) Circle(1, scaleFactor) ...
        ) ...
    );
end
